/**
 * 请求日志中间件属性测试
 * Property 2: Request ID Propagation
 * Validates: Requirements 1.6, 2.3, 2.4
 */

import { describe, it, expect, vi, beforeEach } from 'vitest'
import * as fc from 'fast-check'
import { generateRequestId, REQUEST_ID_HEADER } from './requestLogger'

describe('Request Logger Middleware', () => {
  /**
   * Property 2: Request ID Propagation
   * For any HTTP request, the request ID generated by Request_Logger
   * SHALL appear in all log entries created during that request's lifecycle.
   * Validates: Requirements 1.6, 2.3, 2.4
   */
  describe('Property 2: Request ID Propagation', () => {
    it('should generate unique request IDs', () => {
      fc.assert(
        fc.property(
          fc.integer({ min: 10, max: 100 }),
          (count) => {
            const ids = new Set<string>()
            
            for (let i = 0; i < count; i++) {
              ids.add(generateRequestId())
            }
            
            // 所有生成的 ID 应该是唯一的
            expect(ids.size).toBe(count)
          }
        ),
        { numRuns: 50 }
      )
    })

    it('should generate valid UUID format', () => {
      fc.assert(
        fc.property(
          fc.constant(null),
          () => {
            const id = generateRequestId()
            
            // UUID v4 格式验证
            const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
            expect(id).toMatch(uuidRegex)
          }
        ),
        { numRuns: 100 }
      )
    })
  })

  describe('Unit Tests', () => {
    it('should export correct header name', () => {
      expect(REQUEST_ID_HEADER).toBe('x-request-id')
    })

    it('should generate different IDs on each call', () => {
      const id1 = generateRequestId()
      const id2 = generateRequestId()
      const id3 = generateRequestId()
      
      expect(id1).not.toBe(id2)
      expect(id2).not.toBe(id3)
      expect(id1).not.toBe(id3)
    })
  })
})
